blank_issues_enabled: false
contact_links:
  - name: PlayerLevelEX 开源仓库
    url: https://github.com/CPJiNan/PlayerLevel
    about: 如果是 PlayerLevelEX 插件的issue提交而不是此文档的，请前往此处
  - name: PlayerLevelEX 群聊
    url: https://qm.qq.com/cgi-bin/qm/qr?k=KHWK457uqBPceUIxr_9IKhdX-SSpCEl9&jump_from=webapi&authKey=wRg7BmMgCQqcbaKirMUCZJm5dkoKkdRG7udpsfSJD66Tx2pDn/3UYB7ZG8qhyBXh
    about: 想要和大家一起讨论问题请前往此处
    